import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'api_service.dart';

/// AI Suggestion model
class AISuggestion {
  final String id;
  final String
      type; // 'service_match', 'price_optimization', 'availability_suggest'
  final String userId;
  final String title;
  final String description;
  final Map<String, dynamic> suggestionData;
  final double confidence;
  final bool isAccepted;
  final bool isActive;
  final DateTime? acceptedAt;
  final DateTime createdAt;
  final DateTime updatedAt;

  const AISuggestion({
    required this.id,
    required this.type,
    required this.userId,
    required this.title,
    required this.description,
    required this.suggestionData,
    required this.confidence,
    required this.isAccepted,
    required this.isActive,
    this.acceptedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  factory AISuggestion.fromJson(Map<String, dynamic> json) {
    return AISuggestion(
      id: json['id'] as String,
      type: json['type'] as String,
      userId: json['user_id'] as String,
      title: json['title'] as String,
      description: json['description'] as String,
      suggestionData: Map<String, dynamic>.from(json['suggestion_data'] ?? {}),
      confidence: (json['confidence'] as num).toDouble(),
      isAccepted: json['is_accepted'] as bool? ?? false,
      isActive: json['is_active'] as bool? ?? true,
      acceptedAt: json['accepted_at'] != null
          ? DateTime.parse(json['accepted_at'] as String)
          : null,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }
}

/// Bid model
class Bid {
  final String id;
  final String projectId;
  final String providerId;
  final double amount;
  final String currency;
  final String proposal;
  final int estimatedDuration; // in days
  final DateTime availableFrom;
  final String status; // 'pending', 'accepted', 'rejected', 'withdrawn'
  final bool isAutoGenerated;
  final DateTime? acceptedAt;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Bid({
    required this.id,
    required this.projectId,
    required this.providerId,
    required this.amount,
    required this.currency,
    required this.proposal,
    required this.estimatedDuration,
    required this.availableFrom,
    required this.status,
    required this.isAutoGenerated,
    this.acceptedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Bid.fromJson(Map<String, dynamic> json) {
    return Bid(
      id: json['id'] as String,
      projectId: json['project_id'] as String,
      providerId: json['provider_id'] as String,
      amount: (json['amount'] as num).toDouble(),
      currency: json['currency'] as String,
      proposal: json['proposal'] as String,
      estimatedDuration: json['estimated_duration'] as int,
      availableFrom: DateTime.parse(json['available_from'] as String),
      status: json['status'] as String,
      isAutoGenerated: json['is_auto_generated'] as bool? ?? false,
      acceptedAt: json['accepted_at'] != null
          ? DateTime.parse(json['accepted_at'] as String)
          : null,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }
}

/// Verification model
class Verification {
  final String id;
  final String userId;
  final String type; // 'identity', 'business', 'address', 'phone', 'email'
  final String status; // 'pending', 'verified', 'rejected', 'expired'
  final Map<String, dynamic> documentData;
  final String? verifiedBy;
  final DateTime? verifiedAt;
  final String? rejectionReason;
  final DateTime? expiresAt;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Verification({
    required this.id,
    required this.userId,
    required this.type,
    required this.status,
    required this.documentData,
    this.verifiedBy,
    this.verifiedAt,
    this.rejectionReason,
    this.expiresAt,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Verification.fromJson(Map<String, dynamic> json) {
    return Verification(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      type: json['type'] as String,
      status: json['status'] as String,
      documentData: Map<String, dynamic>.from(json['document_data'] ?? {}),
      verifiedBy: json['verified_by'] as String?,
      verifiedAt: json['verified_at'] != null
          ? DateTime.parse(json['verified_at'] as String)
          : null,
      rejectionReason: json['rejection_reason'] as String?,
      expiresAt: json['expires_at'] != null
          ? DateTime.parse(json['expires_at'] as String)
          : null,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }
}

/// Admin service for managing platform operations
class AdminService {
  final ApiService _apiService;

  AdminService(this._apiService);

  // === AI SUGGESTIONS & FEEDBACK ===

  /// Get AI suggestions for user
  Future<ApiResponse<List<AISuggestion>>> getAISuggestions({
    String? type,
    String? userId,
    bool? activeOnly,
    double? minConfidence,
    int? page,
    int? pageSize,
  }) async {
    final queryParams = <String, String>{};
    if (type != null) queryParams['type'] = type;
    if (userId != null) queryParams['user_id'] = userId;
    if (activeOnly != null) queryParams['active_only'] = '$activeOnly';
    if (minConfidence != null) {
      queryParams['min_confidence'] = minConfidence.toString();
    }
    if (page != null) queryParams['page'] = page.toString();
    if (pageSize != null) queryParams['page_size'] = pageSize.toString();

    return _apiService.get<List<AISuggestion>>(
      '/ai/suggestions/',
      queryParameters: queryParams.isNotEmpty ? queryParams : null,
      fromJson: (data) => (data['results'] as List)
          .map((suggestion) => AISuggestion.fromJson(suggestion))
          .toList(),
    );
  }

  /// Accept AI suggestion
  Future<ApiResponse<AISuggestion>> acceptAISuggestion(
      String suggestionId) async {
    return _apiService.post<AISuggestion>(
      '/ai/suggestions/$suggestionId/accept/',
      fromJson: (data) => AISuggestion.fromJson(data),
    );
  }

  /// Reject AI suggestion
  Future<ApiResponse<AISuggestion>> rejectAISuggestion(
    String suggestionId, {
    String? reason,
  }) async {
    return _apiService.post<AISuggestion>(
      '/ai/suggestions/$suggestionId/reject/',
      body: {
        if (reason != null) 'reason': reason,
      },
      fromJson: (data) => AISuggestion.fromJson(data),
    );
  }

  /// Submit AI feedback
  Future<ApiResponse<Map<String, dynamic>>> submitAIFeedback({
    required String type,
    required String content,
    String? suggestionId,
    Map<String, dynamic>? metadata,
  }) async {
    return _apiService.post<Map<String, dynamic>>(
      '/ai/feedback/',
      body: {
        'type': type,
        'content': content,
        if (suggestionId != null) 'suggestion_id': suggestionId,
        if (metadata != null) 'metadata': metadata,
      },
      fromJson: (data) => data,
    );
  }

  /// Get AI feedback logs
  Future<ApiResponse<List<Map<String, dynamic>>>> getAIFeedbackLogs({
    String? type,
    DateTime? startDate,
    DateTime? endDate,
    int? page,
    int? pageSize,
  }) async {
    final queryParams = <String, String>{};
    if (type != null) queryParams['type'] = type;
    if (startDate != null) {
      queryParams['start_date'] = startDate.toIso8601String().split('T')[0];
    }
    if (endDate != null) {
      queryParams['end_date'] = endDate.toIso8601String().split('T')[0];
    }
    if (page != null) queryParams['page'] = page.toString();
    if (pageSize != null) queryParams['page_size'] = pageSize.toString();

    return _apiService.get<List<Map<String, dynamic>>>(
      '/ai/feedback/logs/',
      queryParameters: queryParams.isNotEmpty ? queryParams : null,
      fromJson: (data) => List<Map<String, dynamic>>.from(data['results']),
    );
  }

  // === ANALYTICS & REPORTS ===

  /// Get platform analytics
  Future<ApiResponse<Map<String, dynamic>>> getPlatformAnalytics({
    DateTime? startDate,
    DateTime? endDate,
    String? groupBy,
    List<String>? metrics,
  }) async {
    final queryParams = <String, String>{};
    if (startDate != null) {
      queryParams['start_date'] = startDate.toIso8601String().split('T')[0];
    }
    if (endDate != null) {
      queryParams['end_date'] = endDate.toIso8601String().split('T')[0];
    }
    if (groupBy != null) queryParams['group_by'] = groupBy;
    if (metrics != null) queryParams['metrics'] = metrics.join(',');

    return _apiService.get<Map<String, dynamic>>(
      '/analytics/platform/',
      queryParameters: queryParams.isNotEmpty ? queryParams : null,
      fromJson: (data) => data,
    );
  }

  /// Get user analytics report
  Future<ApiResponse<Map<String, dynamic>>> getUserAnalytics({
    String? userId,
    String? userType,
    DateTime? startDate,
    DateTime? endDate,
    String? groupBy,
  }) async {
    final queryParams = <String, String>{};
    if (userId != null) queryParams['user_id'] = userId;
    if (userType != null) queryParams['user_type'] = userType;
    if (startDate != null) {
      queryParams['start_date'] = startDate.toIso8601String().split('T')[0];
    }
    if (endDate != null) {
      queryParams['end_date'] = endDate.toIso8601String().split('T')[0];
    }
    if (groupBy != null) queryParams['group_by'] = groupBy;

    return _apiService.get<Map<String, dynamic>>(
      '/analytics/users/',
      queryParameters: queryParams.isNotEmpty ? queryParams : null,
      fromJson: (data) => data,
    );
  }

  /// Get revenue analytics
  Future<ApiResponse<Map<String, dynamic>>> getRevenueAnalytics({
    DateTime? startDate,
    DateTime? endDate,
    String? groupBy,
    String? currency,
  }) async {
    final queryParams = <String, String>{};
    if (startDate != null) {
      queryParams['start_date'] = startDate.toIso8601String().split('T')[0];
    }
    if (endDate != null) {
      queryParams['end_date'] = endDate.toIso8601String().split('T')[0];
    }
    if (groupBy != null) queryParams['group_by'] = groupBy;
    if (currency != null) queryParams['currency'] = currency;

    return _apiService.get<Map<String, dynamic>>(
      '/analytics/revenue/',
      queryParameters: queryParams.isNotEmpty ? queryParams : null,
      fromJson: (data) => data,
    );
  }

  /// Generate custom report
  Future<ApiResponse<Map<String, dynamic>>> generateCustomReport({
    required String reportType,
    required Map<String, dynamic> parameters,
    String? format, // 'json', 'csv', 'pdf'
  }) async {
    return _apiService.post<Map<String, dynamic>>(
      '/analytics/reports/generate/',
      body: {
        'report_type': reportType,
        'parameters': parameters,
        if (format != null) 'format': format,
      },
      fromJson: (data) => data,
    );
  }

  // === USER MANAGEMENT ===

  /// Get all users with filters
  Future<ApiResponse<List<Map<String, dynamic>>>> getAllUsers({
    String? userType,
    String? status,
    bool? isVerified,
    DateTime? registeredAfter,
    DateTime? registeredBefore,
    String? location,
    int? page,
    int? pageSize,
  }) async {
    final queryParams = <String, String>{};
    if (userType != null) queryParams['user_type'] = userType;
    if (status != null) queryParams['status'] = status;
    if (isVerified != null) queryParams['is_verified'] = '$isVerified';
    if (registeredAfter != null) {
      queryParams['registered_after'] =
          registeredAfter.toIso8601String().split('T')[0];
    }
    if (registeredBefore != null) {
      queryParams['registered_before'] =
          registeredBefore.toIso8601String().split('T')[0];
    }
    if (location != null) queryParams['location'] = location;
    if (page != null) queryParams['page'] = page.toString();
    if (pageSize != null) queryParams['page_size'] = pageSize.toString();

    return _apiService.get<List<Map<String, dynamic>>>(
      '/admin/users/',
      queryParameters: queryParams.isNotEmpty ? queryParams : null,
      fromJson: (data) => List<Map<String, dynamic>>.from(data['results']),
    );
  }

  /// Suspend user account
  Future<ApiResponse<Map<String, dynamic>>> suspendUser(
    String userId, {
    required String reason,
    DateTime? suspendUntil,
  }) async {
    return _apiService.post<Map<String, dynamic>>(
      '/admin/users/$userId/suspend/',
      body: {
        'reason': reason,
        if (suspendUntil != null)
          'suspend_until': suspendUntil.toIso8601String(),
      },
      fromJson: (data) => data,
    );
  }

  /// Unsuspend user account
  Future<ApiResponse<Map<String, dynamic>>> unsuspendUser(String userId) async {
    return _apiService.post<Map<String, dynamic>>(
      '/admin/users/$userId/unsuspend/',
      fromJson: (data) => data,
    );
  }

  /// Verify user manually
  Future<ApiResponse<Map<String, dynamic>>> verifyUser(
    String userId, {
    String? verificationNotes,
  }) async {
    return _apiService.post<Map<String, dynamic>>(
      '/admin/users/$userId/verify/',
      body: {
        if (verificationNotes != null) 'verification_notes': verificationNotes,
      },
      fromJson: (data) => data,
    );
  }

  // === SERVICE MANAGEMENT ===

  /// Get all services with admin filters
  Future<ApiResponse<List<Map<String, dynamic>>>> getAllServices({
    String? status,
    String? categoryId,
    String? providerId,
    bool? needsReview,
    DateTime? createdAfter,
    DateTime? createdBefore,
    int? page,
    int? pageSize,
  }) async {
    final queryParams = <String, String>{};
    if (status != null) queryParams['status'] = status;
    if (categoryId != null) queryParams['category_id'] = categoryId;
    if (providerId != null) queryParams['provider_id'] = providerId;
    if (needsReview != null) queryParams['needs_review'] = '$needsReview';
    if (createdAfter != null) {
      queryParams['created_after'] =
          createdAfter.toIso8601String().split('T')[0];
    }
    if (createdBefore != null) {
      queryParams['created_before'] =
          createdBefore.toIso8601String().split('T')[0];
    }
    if (page != null) queryParams['page'] = page.toString();
    if (pageSize != null) queryParams['page_size'] = pageSize.toString();

    return _apiService.get<List<Map<String, dynamic>>>(
      '/admin/services/',
      queryParameters: queryParams.isNotEmpty ? queryParams : null,
      fromJson: (data) => List<Map<String, dynamic>>.from(data['results']),
    );
  }

  /// Approve service
  Future<ApiResponse<Map<String, dynamic>>> approveService(
    String serviceId, {
    String? adminNotes,
  }) async {
    return _apiService.post<Map<String, dynamic>>(
      '/admin/services/$serviceId/approve/',
      body: {
        if (adminNotes != null) 'admin_notes': adminNotes,
      },
      fromJson: (data) => data,
    );
  }

  /// Reject service
  Future<ApiResponse<Map<String, dynamic>>> rejectService(
    String serviceId, {
    required String reason,
    String? adminNotes,
  }) async {
    return _apiService.post<Map<String, dynamic>>(
      '/admin/services/$serviceId/reject/',
      body: {
        'reason': reason,
        if (adminNotes != null) 'admin_notes': adminNotes,
      },
      fromJson: (data) => data,
    );
  }

  /// Feature service
  Future<ApiResponse<Map<String, dynamic>>> featureService(
    String serviceId, {
    DateTime? featuredUntil,
  }) async {
    return _apiService.post<Map<String, dynamic>>(
      '/admin/services/$serviceId/feature/',
      body: {
        if (featuredUntil != null)
          'featured_until': featuredUntil.toIso8601String(),
      },
      fromJson: (data) => data,
    );
  }

  // === HEALTH CHECKS ===

  /// Get system health status
  Future<ApiResponse<Map<String, dynamic>>> getSystemHealth() async {
    return _apiService.get<Map<String, dynamic>>(
      '/health/',
      fromJson: (data) => data,
    );
  }

  /// Get database health
  Future<ApiResponse<Map<String, dynamic>>> getDatabaseHealth() async {
    return _apiService.get<Map<String, dynamic>>(
      '/health/db/',
      fromJson: (data) => data,
    );
  }

  // === SYNC OPERATIONS ===

  /// Trigger full system sync
  Future<ApiResponse<Map<String, dynamic>>> triggerFullSync() async {
    return _apiService.post<Map<String, dynamic>>(
      '/sync/full/',
      fromJson: (data) => data,
    );
  }

  /// Trigger user data sync
  Future<ApiResponse<Map<String, dynamic>>> triggerUserSync(
      String userId) async {
    return _apiService.post<Map<String, dynamic>>(
      '/sync/users/$userId/',
      fromJson: (data) => data,
    );
  }

  /// Trigger payment sync
  Future<ApiResponse<Map<String, dynamic>>> triggerPaymentSync() async {
    return _apiService.post<Map<String, dynamic>>(
      '/sync/payments/',
      fromJson: (data) => data,
    );
  }

  /// Get sync status
  Future<ApiResponse<Map<String, dynamic>>> getSyncStatus() async {
    return _apiService.get<Map<String, dynamic>>(
      '/sync/status/',
      fromJson: (data) => data,
    );
  }

  /// Get sync history
  Future<ApiResponse<List<Map<String, dynamic>>>> getSyncHistory({
    String? syncType,
    DateTime? startDate,
    DateTime? endDate,
    int? page,
    int? pageSize,
  }) async {
    final queryParams = <String, String>{};
    if (syncType != null) queryParams['sync_type'] = syncType;
    if (startDate != null) {
      queryParams['start_date'] = startDate.toIso8601String().split('T')[0];
    }
    if (endDate != null) {
      queryParams['end_date'] = endDate.toIso8601String().split('T')[0];
    }
    if (page != null) queryParams['page'] = page.toString();
    if (pageSize != null) queryParams['page_size'] = pageSize.toString();

    return _apiService.get<List<Map<String, dynamic>>>(
      '/sync/history/',
      queryParameters: queryParams.isNotEmpty ? queryParams : null,
      fromJson: (data) => List<Map<String, dynamic>>.from(data['results']),
    );
  }

  // === VERIFICATIONS ===

  /// Get all verification requests
  Future<ApiResponse<List<Verification>>> getVerificationRequests({
    String? type,
    String? status,
    String? userId,
    DateTime? submittedAfter,
    DateTime? submittedBefore,
    int? page,
    int? pageSize,
  }) async {
    final queryParams = <String, String>{};
    if (type != null) queryParams['type'] = type;
    if (status != null) queryParams['status'] = status;
    if (userId != null) queryParams['user_id'] = userId;
    if (submittedAfter != null) {
      queryParams['submitted_after'] =
          submittedAfter.toIso8601String().split('T')[0];
    }
    if (submittedBefore != null) {
      queryParams['submitted_before'] =
          submittedBefore.toIso8601String().split('T')[0];
    }
    if (page != null) queryParams['page'] = page.toString();
    if (pageSize != null) queryParams['page_size'] = pageSize.toString();

    return _apiService.get<List<Verification>>(
      '/verifications/',
      queryParameters: queryParams.isNotEmpty ? queryParams : null,
      fromJson: (data) => (data['results'] as List)
          .map((verification) => Verification.fromJson(verification))
          .toList(),
    );
  }

  /// Submit verification request
  Future<ApiResponse<Verification>> submitVerification({
    required String type,
    required Map<String, dynamic> documentData,
  }) async {
    return _apiService.post<Verification>(
      '/verifications/',
      body: {
        'type': type,
        'document_data': documentData,
      },
      fromJson: (data) => Verification.fromJson(data),
    );
  }

  /// Process verification request
  Future<ApiResponse<Verification>> processVerification(
    String verificationId, {
    required String action, // 'approve', 'reject'
    String? reason,
    String? adminNotes,
  }) async {
    return _apiService.post<Verification>(
      '/verifications/$verificationId/process/',
      body: {
        'action': action,
        if (reason != null) 'reason': reason,
        if (adminNotes != null) 'admin_notes': adminNotes,
      },
      fromJson: (data) => Verification.fromJson(data),
    );
  }

  // === BIDS MANAGEMENT ===

  /// Get all bids
  Future<ApiResponse<List<Bid>>> getAllBids({
    String? status,
    String? projectId,
    String? providerId,
    DateTime? submittedAfter,
    DateTime? submittedBefore,
    double? minAmount,
    double? maxAmount,
    int? page,
    int? pageSize,
  }) async {
    final queryParams = <String, String>{};
    if (status != null) queryParams['status'] = status;
    if (projectId != null) queryParams['project_id'] = projectId;
    if (providerId != null) queryParams['provider_id'] = providerId;
    if (submittedAfter != null) {
      queryParams['submitted_after'] =
          submittedAfter.toIso8601String().split('T')[0];
    }
    if (submittedBefore != null) {
      queryParams['submitted_before'] =
          submittedBefore.toIso8601String().split('T')[0];
    }
    if (minAmount != null) queryParams['min_amount'] = minAmount.toString();
    if (maxAmount != null) queryParams['max_amount'] = maxAmount.toString();
    if (page != null) queryParams['page'] = page.toString();
    if (pageSize != null) queryParams['page_size'] = pageSize.toString();

    return _apiService.get<List<Bid>>(
      '/bids/',
      queryParameters: queryParams.isNotEmpty ? queryParams : null,
      fromJson: (data) =>
          (data['results'] as List).map((bid) => Bid.fromJson(bid)).toList(),
    );
  }

  /// Create bid
  Future<ApiResponse<Bid>> createBid({
    required String projectId,
    required double amount,
    required String currency,
    required String proposal,
    required int estimatedDuration,
    required DateTime availableFrom,
  }) async {
    return _apiService.post<Bid>(
      '/bids/',
      body: {
        'project_id': projectId,
        'amount': amount,
        'currency': currency,
        'proposal': proposal,
        'estimated_duration': estimatedDuration,
        'available_from': availableFrom.toIso8601String(),
      },
      fromJson: (data) => Bid.fromJson(data),
    );
  }

  /// Update bid
  Future<ApiResponse<Bid>> updateBid(
    String bidId,
    Map<String, dynamic> updates,
  ) async {
    return _apiService.patch<Bid>(
      '/bids/$bidId/',
      body: updates,
      fromJson: (data) => Bid.fromJson(data),
    );
  }

  /// Accept bid
  Future<ApiResponse<Bid>> acceptBid(String bidId) async {
    return _apiService.post<Bid>(
      '/bids/$bidId/accept/',
      fromJson: (data) => Bid.fromJson(data),
    );
  }

  /// Reject bid
  Future<ApiResponse<Bid>> rejectBid(
    String bidId, {
    String? reason,
  }) async {
    return _apiService.post<Bid>(
      '/bids/$bidId/reject/',
      body: {
        if (reason != null) 'reason': reason,
      },
      fromJson: (data) => Bid.fromJson(data),
    );
  }

  /// Withdraw bid
  Future<ApiResponse<Bid>> withdrawBid(String bidId) async {
    return _apiService.post<Bid>(
      '/bids/$bidId/withdraw/',
      fromJson: (data) => Bid.fromJson(data),
    );
  }

  // === SYSTEM CONFIGURATION ===

  /// Get system configuration
  Future<ApiResponse<Map<String, dynamic>>> getSystemConfig() async {
    return _apiService.get<Map<String, dynamic>>(
      '/admin/config/',
      fromJson: (data) => data,
    );
  }

  /// Update system configuration
  Future<ApiResponse<Map<String, dynamic>>> updateSystemConfig(
    Map<String, dynamic> config,
  ) async {
    return _apiService.patch<Map<String, dynamic>>(
      '/admin/config/',
      body: config,
      fromJson: (data) => data,
    );
  }

  /// Get feature flags
  Future<ApiResponse<Map<String, dynamic>>> getFeatureFlags() async {
    return _apiService.get<Map<String, dynamic>>(
      '/admin/features/',
      fromJson: (data) => data,
    );
  }

  /// Update feature flag
  Future<ApiResponse<Map<String, dynamic>>> updateFeatureFlag(
    String flagName,
    bool enabled,
  ) async {
    return _apiService.patch<Map<String, dynamic>>(
      '/admin/features/',
      body: {flagName: enabled},
      fromJson: (data) => data,
    );
  }

  // === AUDIT LOGS ===

  /// Get audit logs
  Future<ApiResponse<List<Map<String, dynamic>>>> getAuditLogs({
    String? action,
    String? userId,
    String? resource,
    DateTime? startDate,
    DateTime? endDate,
    int? page,
    int? pageSize,
  }) async {
    final queryParams = <String, String>{};
    if (action != null) queryParams['action'] = action;
    if (userId != null) queryParams['user_id'] = userId;
    if (resource != null) queryParams['resource'] = resource;
    if (startDate != null) {
      queryParams['start_date'] = startDate.toIso8601String().split('T')[0];
    }
    if (endDate != null) {
      queryParams['end_date'] = endDate.toIso8601String().split('T')[0];
    }
    if (page != null) queryParams['page'] = page.toString();
    if (pageSize != null) queryParams['page_size'] = pageSize.toString();

    return _apiService.get<List<Map<String, dynamic>>>(
      '/admin/audit_logs/',
      queryParameters: queryParams.isNotEmpty ? queryParams : null,
      fromJson: (data) => List<Map<String, dynamic>>.from(data['results']),
    );
  }

  /// Export audit logs
  Future<ApiResponse<Map<String, dynamic>>> exportAuditLogs({
    String? format, // 'csv', 'json', 'xlsx'
    DateTime? startDate,
    DateTime? endDate,
    String? action,
    String? userId,
  }) async {
    return _apiService.post<Map<String, dynamic>>(
      '/admin/audit_logs/export/',
      body: {
        if (format != null) 'format': format,
        if (startDate != null)
          'start_date': startDate.toIso8601String().split('T')[0],
        if (endDate != null)
          'end_date': endDate.toIso8601String().split('T')[0],
        if (action != null) 'action': action,
        if (userId != null) 'user_id': userId,
      },
      fromJson: (data) => data,
    );
  }
}

/// Provider for AdminService
final adminServiceProvider = Provider<AdminService>((ref) {
  return AdminService(ApiService());
});
